### ISSUE TITLE
Sass 3.3 parent selector suffixes

### ISSUE THREAD

**Issue by isGabe** [P233/Atom-Syntax-highlighting-for-Sass#1]
I was hoping this package would fix the issue of [Sass 3.3 parent selector suffixes](http://thesassway.com/news/sass-3-3-released#parent-selector-suffixes) being [highlighted as error/illegal](http://discuss.atom.io/t/sass-syntax-highlighting-not-working-with-sass-3-3-parent-selector-suffixes/9762), but this doesn't seem to be the case. Is this easy to fix?

**Comment by P233** [comment]
Hi @FStop , the new [sublime version](https://github.com/P233/Syntax-highlighting-for-Sass) does support Sass 3.3 syntax and has some new features. However it got one little problem on Atom. I will update this package once I fixed it. It won't take too long.

**Comment by jakecleary** [comment]
Worked fine for me once I disabled the official language pack.

**Comment by isGabe** [comment]
+1 for turning off the official language pack. Without that this package works just fine. Sorry for the bogus issue.

**Comment by P233** [comment]
I've updated this pakcage and added support for Sass 3.3 and 3.4
